TECH-368
bcgov-elmsd/workbc-ches-email-blast pull request #29
Opened 2023-07-28 21:43 UTC by trista-d

- Created uid in Submission table, to match entries in Email table
- Added a check to prevent users from submitting more than one form

2023-07-28 23:10 UTC, npham49 commented
Did you update the new prisma.schema with the uid?

2023-07-28 23:13 UTC, npham49 requested changes
Have a look at my comments!

2023-07-28 23:13 UTC, npham49 commented on packages/forms-frontend/app/api/form/route.ts
> +        if (submission) throw new Error("You have already submitted this form")
Let's also add an error handler on the front-end to show this in the toast error message

2023-07-28 23:13 UTC, npham49 commented on packages/forms-frontend/app/api/form/route.ts
> +        if (submission) throw new Error("You have already submitted this form")
Might also have to double check if we want them to submit multiple or not, not sure if it's part of the requirements.

2023-07-28 23:28 UTC, trista-d commented on packages/forms-frontend/app/api/form/route.ts
> +        if (submission) throw new Error("You have already submitted this form")
"You have already submitted this form" shows up in the toast already! Should I ask Priscilla about this functionality on Monday? My reasoning right now is that without it, a single user can bombard a centre with emails. If they can submit multiple forms, we should probably limit it to a certain number.

2023-07-28 23:29 UTC, trista-d commented
> Did you update the new prisma.schema with the uid?

I just forgot to commit it, sorry!

2023-07-28 23:30 UTC, npham49 commented on packages/forms-frontend/app/api/form/route.ts
> +        if (submission) throw new Error("You have already submitted this form")
Yes please! I'd also prefer that they submit only once but I can see people making an argument for the case of accidental submissions.

2023-08-01 22:12 UTC, trista-d commented on packages/forms-frontend/app/api/form/route.ts
> +        if (submission) throw new Error("You have already submitted this form")
We're good to allow clients to only submit once!

2023-08-02 18:59 UTC, npham49 requested changes
Just 1 small comments then you're free to merge your changes

2023-08-02 18:59 UTC, npham49 commented on packages/forms-frontend/app/layout.tsx
>      description: "Generated by create next app"
Change this to "Short form to contact a WorkBC Centre"

2023-08-02 20:21 UTC, merged